glob.o: glob.cc ../stypes.h ../ddconfig.h glob.h
inst.o: inst.cc ../ddconfig.h glob.h ../stypes.h xacl.h ../sim.src/uccl.h \
  ../pobjcl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
  ../cmd.src/newcmdcl.h ../sim.src/appcl.h ../sim.src/argcl.h \
  ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
  ../sim.src/memcl.h ../errorcl.h ../sim.src/brkcl.h regsxa.h instcl.h \
  inst_gen.cc
inst_gen.o: inst_gen.cc
simxa.o: simxa.cc simxacl.h ../sim.src/simcl.h ../pobjcl.h ../ddconfig.h \
  ../pobjt.h ../cmd.src/newcmdcl.h ../sim.src/appcl.h ../sim.src/argcl.h \
  ../stypes.h ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/memcl.h ../errorcl.h \
  ../sim.src/brkcl.h xacl.h regsxa.h instcl.h
sxa.o: sxa.cc ../sim.src/appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
  ../sim.src/argcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
  ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/memcl.h ../errorcl.h \
  ../sim.src/brkcl.h simxacl.h
xa.o: xa.cc ../ddconfig.h ../i_string.h ../pobjcl.h ../pobjt.h \
  ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../sim.src/appcl.h \
  ../sim.src/argcl.h ../stypes.h ../gui.src/guicl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/memcl.h ../errorcl.h ../sim.src/brkcl.h xacl.h regsxa.h \
  instcl.h glob.h
