glob.o: glob.cc ../stypes.h ../ddconfig.h
inst.o: inst.cc ../ddconfig.h stm8cl.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../appcl.h ../pobjcl.h \
 ../optioncl.h ../stypes.h ../sim.src/argcl.h ../sim.src/simcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../sim.src/argcl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h regsstm8.h instcl.h stm8mac.h
simstm8.o: simstm8.cc simstm8cl.h ../sim.src/simcl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h \
 ../sim.src/argcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/argcl.h stm8cl.h \
 ../sim.src/uccl.h regsstm8.h instcl.h
sstm8.o: sstm8.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../appcl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/argcl.h simstm8cl.h
stm8.o: stm8.cc ../ddconfig.h ../i_string.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../appcl.h ../pobjcl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/argcl.h stm8cl.h ../sim.src/uccl.h \
 regsstm8.h instcl.h glob.h stm8mac.h
